config/routes.rb
Rails.application.routes.draw do
  resources :corners
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "corners#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/corner.rb
class Corner < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/corners_controller.rb
class CornersController < ApplicationController
  before_action :set_corner, only: %i[ show edit update destroy ]

  # GET /corners or /corners.json
  def index
    @corners = Corner.all
  end

  # GET /corners/1 or /corners/1.json
  def show
    id = params[:id]
    @corner = Corner.where(id: id).first
  end

  # GET /corners/new
  def new
    @corner = Corner.new
  end

  # GET /corners/1/edit
  def edit
  end

  # POST /corners or /corners.json
  def create
    @corner = Corner.new(corner_params)

    respond_to do |format|
      if @corner.save
        format.html { redirect_to corner_url(@corner), notice: "Corner was successfully created." }
        format.json { render :show, status: :created, location: @corner }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @corner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /corners/1 or /corners/1.json
  def update
    respond_to do |format|
      if @corner.update(corner_params)
        format.html { redirect_to corner_url(@corner), notice: "Corner was successfully updated." }
        format.json { render :show, status: :ok, location: @corner }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @corner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corners/1 or /corners/1.json
  def destroy
    @corner.destroy

    respond_to do |format|
      format.html { redirect_to corners_url, notice: "Corner was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_corner
      @corner = Corner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def corner_params
      params.require(:corner).permit(:name, :velocity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corners_helper.rb
module CornersHelper
end

app/views/corners/_corner.html.erb
<div id="<%= dom_id corner %>">
  <p>
    <strong>Name:</strong>
    <%= corner.name %>
  </p>

  <p>
    <strong>Velocity:</strong>
    <%= corner.velocity %>
  </p>

</div>

app/views/corners/_form.html.erb
<%= form_with(model: corner) do |form| %>
  <% if corner.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(corner.errors.count, "error") %> prohibited this corner from being saved:</h2>

      <ul>
        <% corner.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :velocity, style: "display: block" %>
    <%= form.text_field :velocity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/corners/edit.html.erb
<h1>Editing corner</h1>

<%= render "form", corner: @corner %>

<br>

<div>
  <%= link_to "Show this corner", @corner %> |
  <%= link_to "Back to corners", corners_path %>
</div>

app/views/corners/index.haml
.list-container
  .h1.mx-5.mt-5 Corners
  .ul.mx-5
    - @corners.each do |i|
      .li.scene-links
        = link_to i.name, corner_path(i.id)

app/views/corners/new.html.erb
<h1>New corner</h1>

<%= render "form", corner: @corner %>

<br>

<div>
  <%= link_to "Back to corners", corners_path %>
</div>

app/views/corners/show.haml
!!!
%html{lang: "en"}
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{charset: "UTF-8"}/
    %title Rain Effect
    :css
      body {
          margin: 0;
          overflow: hidden;
          background-color: black;
      }

      #canvas-container {
      }
      #titel{
          text-align: center;
          color: White;
          font-family: "lores-12", sans-serif;
          font-weight: 700;
          font-style: normal;
      }

      #color-pick-container{
          display: flex;
          justify-content: space-evenly;
          margin-top: 20px;
      }
    %link{href: "https://use.typekit.net/zgn8bht.css", rel: "stylesheet"}/
  %body
    :javascript
      SC.initialize({
          client_id: 'YOUR_CLIENT_ID',
          redirect_uri: 'https://example.com/callback'
      });
    #inner-container{style: "display: flex;"}
      %div
        %h1#titel
          Carls Chill Corner
        %p#color-input.text-transparent
          0xa0C0ff
        %p#scene-input.text-transparent
          = @corner.name
        %div
          #soundcloud-widget-container
            %iframe{allow: "autoplay", frameborder: "no", height: "450", scrolling: "no", src: "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/35453135&color=%23cf4900&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true", width: "100%"}
          %div{style: "font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"}
            %a{href: "https://soundcloud.com/minecraft-official", style: "color: #cccccc; text-decoration: none;", target: "_blank", title: "Minecraft Official"} Minecraft Official
            %a{href: "https://soundcloud.com/minecraft-official/sets/minecraft-volume-alpha", style: "color: #cccccc; text-decoration: none;", target: "_blank", title: "Minecraft - Volume Alpha"} Minecraft - Volume Alpha
        #color-pick-container
          %button#colorInput1.jscolor{class: "{valueElement:'color_value'}", onchange: "config.changeStrokeCol(this.jscolor)"}
            Stroke Color
          %button#update-button Update Color Input
        :javascript
          const formField = document.getElementById('form-field');
          const updateButton = document.getElementById('update-button');
          const colorInput = document.getElementById('color-input');

          updateButton.addEventListener('click', function() {
              colorInput.textContent = document.getElementById('colorInput1').jscolor.toHEXString();
              console.log("hello");
          });

          function setDefaultColor() {
              var colorInput = document.getElementById("colorInput1");
              colorInput.jscolor.fromString("A0C0BF");
              colorInput.textContent = document.getElementById('colorInput1').jscolor.toHEXString();
          }

          window.addEventListener("load", setDefaultColor);
      #canvas-container

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Carls Chill Corner
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    :css
      @import url('https://fonts.googleapis.com/css2?family=Chakra+Petch:wght@700&display=swap');
    %link{href: "https://use.typekit.net/zgn8bht.css", rel: "stylesheet"}/
    %link{href: "https://use.typekit.net/ydu3jtc.css", rel: "stylesheet"}/
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true

  %body
    %nav.navbar.navbar-expand-lg.navbar-light.bg-transparent
      %p.navbar-brand.text-white.chill-logo.mt-3 Carls Chill Corner
      %ul.navbar-nav.mr-auto
        %li.nav-item.mx-5.nav-link2
          = link_to "Home", root_path(), class: "nav-link2"
    = yield